### ISSUE TITLE
Flex grid support

### ISSUE THREAD

**Issue by mdorn** [juliancwirko/meteor-npm-foundation-test#3] opened 2016-06-19 16:48 UTC
Hi Julian -- I'm using the approach you've described, and I have a Foundation-based project that uses [Flex Grid](http://foundation.zurb.com/sites/docs/flex-grid.html).  Importing this component in my CSS file like so:

```
@include foundation-flex-classes;
@include foundation-flex-grid;
```

 causes Meteor startup to fail:

```
  => Errors prevented startup:                  

     While processing files with fourseven:scss (for target web.browser):
     /client/app.scss: Scss compiler error: argument `$map` of `map-has-key($map, $key)` must be a map

     Backtrace:
     breakpoint:216, in function `map-has-key`
     breakpoint:216, in function `-zf-get-bp-val`
     flex-grid:250, in mixin `@content`
     mixins:231, in mixin `@content`
     breakpoint:143, in mixin `breakpoint`
     mixins:230, in mixin `-zf-each-breakpoint`
     flex-grid:192, in mixin `foundation-flex-grid`
     {}/client/app.scss:51
```

All of the other includes work well; commenting out the `foundation-flex-grid` line (line 51, as referenced in the backtrace) makes everything start OK, but my design relies on Flex Grid.  I'm guessing this is a problem with `fourseven:scss`. Any ideas?

**Comment by juliancwirko** [comment] 2016-06-19 17:40
Hi, it looks like node-sass incompatibility but Foundation needs node-sass in version 3.4.2+ ([docs](http://foundation.zurb.com/sites/docs/sass.html#compatibility)) and fourseven:scss uses 3.4.2 so it should work. Maybe this is a bug in Foundation itself or you have something wrong in your configuration. Hard to say. Do you have any reproduction repository?

**Comment by mdorn** [comment] 2016-06-19 18:34
Thanks @juliancwirko -- I don't have a reproduction repo, but if I get some time, I'll create one.  For now rolling back to Foundation v6.0.6 seems to prevent the error.

**Comment by mdorn** [comment] 2016-06-23 20:33
@juliancwirko - feel free to mark this issue as invalid and close. There's a problem with the settings file I'm including.

**Comment by juliancwirko** [comment] 2016-06-23 20:52
ok, closing :)

**Closed as completed by juliancwirko** 2016-06-23 20:52 UTC
